jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /parqueadero
      session:
         timeout: 21600s

spring:
   flyway.baseline-on-migrate : true
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://localhost:5432/adn
      username: postgres
      password: root
      hikari:
         poolName: pool